#ifndef CONFIG_H
#define CONFIG_H

// COLORS
#define WHITE 65535
#define BLUE 255

// SCALE
#define HEADLINE_SCALE 5
#define BUTTON_BIGGER_SCALE 3
#define BUTTON_LOWER_SCALE 2
#define INFO_BIGGER_SCALE 3
#define INFO_LOWER_SCALE 2

// MM = MAIN MENU, POSITIONS
#define MM_PONG_POS_X 140
#define MM_PONG_POS_Y 10
#define MM_ONE_P_POS_X 120
#define MM_ONE_P_POS_Y 140
#define MM_TWO_P_POS_X 125
#define MM_TWO_P_POS_Y 180
#define MM_EXIT_POS_X 125
#define MM_EXIT_POS_Y 180

// OPM = ONE PLAYER MENU, POSITIONS
#define OPM_HEADLINE_POS_X 10
#define OPM_HEADLINE_POS_Y 10
#define OPM_SCORE_POS_X 20
#define OPM_SCORE_POS_Y 20
#define OPM_DIFFICULTY_POS_X 30
#define OPM_DIFFICULTY_POS_Y 30
#define OPM_EASY_POS_X 140
#define OPM_EASY_POS_Y 10
#define OPM_MEDIUM_POS_X 140
#define OPM_MEDIUM_POS_Y 10
#define OPM_HARD_POS_X 140
#define OPM_HARD_POS_Y 10
#define OPM_GO_BACK_POS_X 140
#define OPM_GO_BACK_POS_Y 10
#define OPM_START_POS_X 140
#define OPM_START_POS_Y 10

// TPM = TWO PLAYER MENU, POSITIONS
#define TPM_HEADLINE_POS_X 10
#define TPM_HEADLINE_POS_Y 10
#define TPM_SCORE_POS_X 20
#define TPM_SCORE_POS_Y 20
#define TPM_GO_BACK_POS_X 140
#define TPM_GO_BACK_POS_Y 10
#define TPM_START_POS_X 140
#define TPM_START_POS_Y 10

// PM = PAUSE MENU, POSITIONS
#define PM_RESUME_POS_X 10
#define PM_RESUME_POS_Y 10
#define PM_RETURN_POS_X 20
#define PM_RETURN_POS_Y 20

// EM = END MENU, POSITIONS
#define EM_FINISHED_POS_X 10
#define EM_FINISHED_POS_Y 10
#define EM_WINNER_POS_X 10
#define EM_WINNER_POS_Y 10
#define EM_MENU_POS_X 10
#define EM_MENU_POS_Y 10
#define EM_EXIT_POS_X 20
#define EM_EXIT_POS_Y 20

#endif /* CONFIG_H */
