#ifndef CONFIG_H
#define CONFIG_H

// COLORS
#define WHITE 65535
#define PURPLE 63519
#define RED 63488
#define YELLOW 65504
#define GREEN 2016
#define BLUE 255

// SCALE
#define HEADLINE_SCALE 5
#define BUTTON_BIGGER_SCALE 3
#define BUTTON_LOWER_SCALE 2
#define INFO_BIGGER_SCALE 3
#define INFO_LOWER_SCALE 2

// MM = MAIN MENU, POSITIONS
#define MM_PONG_POS_X 140
#define MM_PONG_POS_Y 10
#define MM_ONE_P_POS_X 140
#define MM_ONE_P_POS_Y 120
#define MM_TWO_P_POS_X 125
#define MM_TWO_P_POS_Y 180
#define MM_EXIT_POS_X 195
#define MM_EXIT_POS_Y 240

// OPM = ONE PLAYER MENU, POSITIONS
#define OPM_HEADLINE_POS_X 70
#define OPM_HEADLINE_POS_Y 10
#define OPM_SCORE_POS_X 55
#define OPM_SCORE_POS_Y 90
#define OPM_DIFFICULTY_POS_X 50
#define OPM_DIFFICULTY_POS_Y 150
#define OPM_EASY_POS_X 80
#define OPM_EASY_POS_Y 200
#define OPM_MEDIUM_POS_X 200
#define OPM_MEDIUM_POS_Y 200
#define OPM_HARD_POS_X 350
#define OPM_HARD_POS_Y 200
#define OPM_GO_BACK_POS_X 50
#define OPM_GO_BACK_POS_Y 250
#define OPM_START_POS_X 300
#define OPM_START_POS_Y 250

// TPM = TWO PLAYER MENU, POSITIONS
#define TPM_HEADLINE_POS_X 50
#define TPM_HEADLINE_POS_Y 10
#define TPM_SCORE_POS_X 55
#define TPM_SCORE_POS_Y 110
#define TPM_GO_BACK_POS_X 50
#define TPM_GO_BACK_POS_Y 200
#define TPM_START_POS_X 300
#define TPM_START_POS_Y 200

// PM = PAUSE MENU, POSITIONS
#define PM_PAUSED_POS_X 90
#define PM_PAUSED_POS_Y 10
#define PM_MENU_POS_X 110
#define PM_MENU_POS_Y 120
#define PM_RESUME_POS_X 160
#define PM_RESUME_POS_Y 180

// EM = END MENU, POSITIONS
#define EM_FINISHED_POS_X 80
#define EM_FINISHED_POS_Y 10
#define EM_WINNER_POS_X 70
#define EM_WINNER_POS_Y 120
#define EM_MENU_POS_X 110
#define EM_MENU_POS_Y 180
#define EM_EXIT_POS_X 195
#define EM_EXIT_POS_Y 240

// SCORES
#define MAX_SCORE 10
#define MIN_SCORE 1

#endif /* CONFIG_H */
